### ISSUE TITLE
allow offloading clutter to individual files

### ISSUE THREAD

**Issue by whatdaybob** [custom-cards/decluttering-card#18]
My decluttering templates are getting rather large and was wondering if I was able to map these to individual files?

Instead of this in my lovelace.yaml

```
decluttering_templates:
  my_first_template:     # This is the name of a template
    default:
      - icon: fire
    card:
      type: custom:button-card
      name: '[[name]]'
      icon: 'mdi:[[icon]]'

  my_second_template:    # This is the name of another template
    card:
      type: custom:vertical-stack-in-card
      cards:
        - type: horizontal-stack
          cards:
            - type: custom:button-card
              entity: '[[entity_1]]'
            - type: custom:button-card
              entity: '[[entity_2]]'

```

we could do something like the views

```
decluttering_templates:
  - !include lovelace/decluttering_templates/my_first_template.yaml
  - !include lovelace/decluttering_templates/my_second_template.yaml
```

is this already possible? I have tried and it doesn't error rendering but says it cant find the template.

**Comment by k1rd3rf** [comment]
Thats already possible:
```
resources:
  - url: /community_plugin/decluttering-card/decluttering-card.js
    type: module

decluttering_templates: !include_dir_named decluttering_templates/
```

I would then create a file for each template `my_first_template.yaml` and `my_second_template.yaml` inside my `decluttering_templates/`-folder.
