### ISSUE TITLE
Error using template

### ISSUE THREAD

**Issue by soloam** [custom-cards/decluttering-card#19]
Hello, I have this template:

```
light_rgb_template:
  card:
    - type: custom:slider-entity-row
      entity: light.[[light_name]]
      style: |
        :host {
          color: {% if is_state('binary_sensor.[[light_name]]_autoon', 'on') %} green {% endif %};
        }
      toggle: true
```

And I use it like this:

```
            - type: custom:decluttering-card
              template: light_rgb_template
              variables:
                - light_name: hallway_tablelight
```

This is replacing my old config:

```
            - type: custom:slider-entity-row
              entity: light.hallway_tablelight
              style: |
                :host {
                  color: {% if is_state('binary_sensor.hallway_tablelight_autoon', 'on') %} green {% endif %};
                }
              toggle: true
```

In the Lovelace I get the error:

```
Cannot read property 'startsWith' of undefined
type: 'custom:decluttering-card'
template: light_rgb_template
variables:
  - light_name: hallway_tablelight
```

What I'm doing wrong? Or is this a bug?

Thank you

**Comment by RomRider** [comment]
the `card` property is not an array:

```yaml
light_rgb_template:
  card:
    type: custom:slider-entity-row
    entity: light.[[light_name]]
    style: |
      :host {
        color: {% if is_state('binary_sensor.[[light_name]]_autoon', 'on') %} green {% endif %};
      }
    toggle: true
```
