### ISSUE TITLE
Feature request: support some templating

### ISSUE THREAD

**Issue by smhgit** [custom-cards/decluttering-card#20]
It will be nice to have an option for some templating.

**Comment by RomRider** [comment]
You have [config-template-card](https://github.com/iantrich/config-template-card) for that. This would be redundant in this card.

**Comment by jchhenderson** [comment]
I think I[ve found a way round this.  is I use the input_select as the entity, I no longer need a template to test for the state.  It would become (in a normal button):
```
- type: 'custom:button-card'
  entity: input_select.light_scene
  ...
  state:
    - value: 'Off'
      styles:
        icon:
          - color: Orange  
        card:
          - border: 2px solid var(--button-card-light-color)
          - -webkit-box-shadow: 0px 0px 9px 3px var(--button-card-light-color)
          - box-shadow: 0px 0px 9px 3px var(--button-card-light-color)
  ...

```

...and that can use a declutter variable :-)
