### ISSUE TITLE
Dividers do not work as template in entities cards since HA 0.107

### ISSUE THREAD

**Issue by ronaldheft** [custom-cards/decluttering-card#22]
Since updating Home Assistant to 0.107, my template, which includes a divider for use in entities lists, no longer works.

I'm receiving this message:

`Unknown type encountered: divider`

<img width="389" alt="Screen Shot 2020-03-21 at 12 23 41 PM" src="https://user-images.githubusercontent.com/1143112/77231091-0bb25580-6b6f-11ea-84f3-f0821dcd66fa.png">

I updated my decluttering card to version 0.4.1 and I have migrated my lovelace resources from `ui-lovelace.yaml` to the `lovelace:` section in my config.

If I specify the divider manually (don't use decluttering-card) the divider works fine.

My template is as follows:

```
large_divider:
  default:
    - opacity: 0.25
  card:
    type: divider
    style:
      background-color: var(--secondary-text-color)
      height: 1px
      margin: 15px auto
      opacity: '[[opacity]]'
```

I'm using the template as follows:

```
type: entities
show_header_toggle: false
entities:
  [ ... entities ... ]
  
  - type: custom:decluttering-card
    template: large_divider

  [ ... entities ... ]
```

Thanks!
