### ISSUE TITLE
Support the Entity card Toggle Header

### ISSUE THREAD

**Issue by soloam** [custom-cards/decluttering-card#23]
Hello I have created a decluttering card to simplify my RGB lights:

```
light_rgb_template:
  card:
    type: custom:slider-entity-row
    entity: light.[[light_name]]
    style: |
      :host {
        color: {% if is_state('binary_sensor.[[light_name]]_autoon', 'on') %} green {% endif %};
      }
    toggle: true
    min: 1
    max: 100
    step: 1 
```

Also tried the variant

```
light_rgb_template:
  card:
    type: custom:slider-entity-row
    entity: '[[entity]]'
    style: |
      :host {
        color: {% if is_state('binary_sensor.[[light_name]]_autoon', 'on') %} green {% endif %};
      }
    toggle: true
    min: 1
    max: 100
    step: 1
```

It works ok, but the "entities" card toggle header does not detect the entity and keeps the header switch off when the entity in the "decluttering-card" is on:

![image](https://user-images.githubusercontent.com/11949987/77378626-64037600-6d6e-11ea-9576-510cd53c264e.png)

Is this possible?

Thamk You

**Comment by RomRider** [comment]
There's an ugly trick that should work (I checked how the code works on the entities card):
```yaml
type: custom:decluttering-card
entity: light.test_light #this would be used by the entities card header
variables:
  - entity: light.test_light # this is for decluttering-card card
```
