### ISSUE TITLE
decluttering-card that has another inside it stopped working in HA 110

### ISSUE THREAD

**Issue by i00** [custom-cards/decluttering-card#26]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
HA 0.110.0+

**Last working release (if known):**
HA 0.109.6

**Browser and Operating System:**

Chrome
Windows 10

**Description of problem:**

A card with another custom:decluttering-card within it doesn't work anymore e.g.:
```yaml
  AndroidTVControl_WithLGNetcastTV:
    card:
      card:
        cards:
          - content: >-
              {% set InitialImage = states.sensor.base_url.state +
              state_attr('media_player.' + '[[Entity_LGNetcastTV_NoDomain]]',
              'entity_picture') %} <img src='{{ InitialImage }}' width=100% 
              onload="setTimeout(() => this.src = '{{ InitialImage }}&' + (new
              Date()).getTime(), 2500)" onerror="this.src = '{{ InitialImage
              }}&' + (new Date()).getTime()">
            ignore_line_breaks: true
            type: 'custom:html-template-card'
          - template: AndroidTVControl
            type: 'custom:decluttering-card'
            variables:
              - Entity: '[[Entity_AndroidTV]]'
        type: 'custom:vertical-stack-in-card'
      conditions:
        - entity: 'media_player.[[Entity_LGNetcastTV_NoDomain]]'
          state_not: 'off'
      type: conditional
    default:
      - Entity_AndroidTV: ''
      - Entity_LGNetcastTV_NoDomain: ''
```

**Javascript errors shown in the web inspector (if applicable):**

```
No JS errors
```

**Additional information:**
