### ISSUE TITLE
Combination of button-card and decluttering-card causing additional empty space

### ISSUE THREAD

**Issue by shreram** [custom-cards/decluttering-card#28]
**Checklist:**

- [ x] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**
0.6.3

**Last working release (if known):**
N/A

**Browser and Operating System:**

arch | x86_64
-- | --
dev | false
docker | true
hassio | false
installation_type | Home Assistant Container
os_name | Linux
os_version | 4.19.107-Unraid
python_version | 3.7.7
timezone | America/Chicago
version | 0.111.2
virtualenv | false

**Description of problem:**

When I use decluttering-card with button-card and it causes additional space after each button.

If I use only button-card then no issues.

```
              - type: custom:decluttering-card
                template: motion_sensors_battery_square
                variables:
                  - name: Bedroom
                  - entity: binary_sensor.wyzesense_777bfd2e
                  - entity2: sensor.tmpl_wyze_br_motion_sensor_battery

              - type: 'custom:button-card'
                template: blank_card_2px_width_style

              - type: custom:decluttering-card
                template: motion_sensors_battery_square
                variables:
                  - name: Laundry
                  - entity: binary_sensor.wyzesense_77a5f319
                  - entity2: sensor.tmpl_wyze_lr_motion_sensor_battery
```

![Screen Shot 2020-06-15 at 4 06 10 PM](https://user-images.githubusercontent.com/16169720/84706186-2e5fca80-af22-11ea-8c22-84a5b696de30.png)

![Screen Shot 2020-06-15 at 4 11 44 PM](https://user-images.githubusercontent.com/16169720/84706662-fad17000-af22-11ea-97d8-4a6653275599.png)

![Screen Shot 2020-06-15 at 4 13 26 PM](https://user-images.githubusercontent.com/16169720/84706810-3ec47500-af23-11ea-8ffd-621337cbf803.png)

**Javascript errors shown in the web inspector (if applicable):**

```
No errors
```

**Additional information:**

**Comment by RomRider** [comment]
Please share the template code also (and the button card template if any).

**Comment by shreram** [comment]
Here is the decluttering template

```
  motion_sensors_battery_square:
    card:
      type: 'custom:button-card'
      template: motion_sensors_square_new3
      name: '[[name]]'
      entity: '[[entity]]'
      custom_fields:
        notification: >
          [[[ return states['[[entity2]]'].state + '%'; ]]]
        battery: >
          [[[
            var batval = states['[[entity2]]'].state;
            if (batval < 10) return `<ha-icon
              icon="mdi:battery-10" style="color: #FF0000;">
              </ha-icon>`
            else if (batval <= 20) return `<ha-icon
              icon="mdi:battery-20" style="color: #ff6600;">
              </ha-icon>`
            else if (batval <= 30) return `<ha-icon
              icon="mdi:battery-30" style="color: #ff9933;">
              </ha-icon>`
            else if (batval <= 40) return `<ha-icon
              icon="mdi:battery-40" style="color: #ffcc00;">
              </ha-icon>`
            else if (batval <= 50) return `<ha-icon
              icon="mdi:battery-50" style="color: #FFFF00;">
              </ha-icon>`
            else if (batval <= 60) return `<ha-icon
              icon="mdi:battery-60" style="color: #FFFF00;">
              </ha-icon>`
            else if (batval <= 70) return `<ha-icon
              icon="mdi:battery-70" style="color: #FFFF00;">
              </ha-icon>`
            else if (batval <= 80) return `<ha-icon
              icon="mdi:battery-80" style="color: #CCFF33;">
              </ha-icon>`
            else if (batval <= 90) return `<ha-icon
              icon="mdi:battery-90" style="color: #66FF33;">
              </ha-icon>`
            else return `<ha-icon icon="mdi:battery" style="color: #279b37;"></ha-icon>`
          ]]]
```

And button-card template:

```
motion_sensors_square_new3:
  template: generic_sensors_square
  show_last_changed: true
  state:
    - id: sensor_on
      icon: mdi:run-fast
    - value: "off"
      icon: mdi:run
  styles:
    label:
      - font-size: 8px
    custom_fields:
      notification:
        - border-radius: 50%
        - position: absolute
        - left: 70%
        - top: 80%
        - height: 20px
        - width: 30px # 20px
        - font-size: 12px
        - line-height: 20px
      battery:
        - border-radius: 50%
        - position: absolute
        - left: 70%
        - top: 10%
        - height: 35px
        - width: 15px
        - font-size: 10px
        - line-height: 20px
```

```
generic_sensors_square:
  name_template: >
    var sensor_name = entity.attributes.friendly_name;
    if (sensor_name.split(' ')[sensor_name.split(' ').length - 1] === 'Door') {
      var sensor_name = sensor_name.replace(' Door', '');
      return sensor_name;
    } else {
      var sensor_name = sensor_name.replace(' Window', '');
      var sensor_name = sensor_name.replace('Left', '(L)');
      var sensor_name = sensor_name.replace('Centre', '(C)');
      var sensor_name = sensor_name.replace('Right', '(R)');
      return sensor_name;
    }
  show_label: true
  show_state: true
  show_entity_picture: true
  label_template: >
    return entity.state === 'on' ? '-MOVEMENT-' : ''  ## Maybe this has to be specific for motion only, if so move it in the motion one
  size: 30%
  styles:
    card:
      - border-radius: 12px
      - width: 90px
      - height: 90px
      - padding-left: 5px
      - padding-right: 5px
      - -webkit-box-shadow: 0px 0px 9px 3px var(--button-card-light-color)
      - box-shadow: 0px 0px 9px 3px var(--button-card-light-color)
    name:
      - justify-self: start
      - padding-left: 3px
      - font-weight: bold
      - font-family: Helvetica
      - font-size: 12px
    label:
      - font-size: 12px
      - font-weight: bold
      - justify-self: start
    state: 
      - font-size: 10px
      - font-family: Helvetica
      - padding: 0px 10px
      - justify-self: start
      - text-transform: capitalize
      - font-weight: bold
      - padding-left: 3px
      - color: var(--button-card-light-color)
    grid:
      - grid-template-areas: '"i" "n" "s" "l"'
      - grid-template-columns: 1fr
    img_cell:
      - align-self: center
      - text-align: start
  state:
    - value: "on"
      id: sensor_on
      styles:
        lock:
          - color: red
          - opacity: 1
        state:
          - color: black
        name:
          - color: black
        label:
          - color: black
        card:
          - border: 2px solid rgb(164,33,75)
          - --paper-card-background-color: rgb(254, 239, 179)
          - box-shadow: 0px 0px 10px 3px var(--paper-card-background-color)  
        icon:
          - color: black
    - value: "off"
      styles:
        lock:
          - color: red
          - opacity: 1
        state:
          - color: red
        card:
          - box-shadow: 0px 0px 8px 2px var(--secondary-text-color)
          - border: 0px 0px 10px 3px rgba(130,70,70,0.75)
  tap_action:
    action: none
  hold_action:
    action: none
```

**Comment by RomRider** [comment]
Thanks.
This is something I can't fix but you can :)

The width of the decluttering-card is defined by the parent horizontal-stack (automatically, it's a flexbox) but you have set the width and height of the button-card in pixels.

Instead replace your width and height of the button-card with `aspect_ration: 1/1`. You'll still have square buttons and they will auto-adapt to the size.

**Comment by shreram** [comment]
darn it. I tried using ```aspect_ratio: 1/1``` in the base template 'generic_sensors_square' and commented out  ```width: 90px  height: 90px``` but the buttons are rather big. 

How do I prevent that?

![Screen Shot 2020-06-16 at 10 44 09 AM](https://user-images.githubusercontent.com/16169720/84799767-5f8fd780-afc2-11ea-9abf-a60a8918bf24.png)

**Comment by RomRider** [comment]
You can add invisible buttons on the left (like 2 for eg) to reduce the overall size:
```
type: custom:button-card
color_type: blank-card
```

**Comment by shreram** [comment]
Bingo! Thank you for the explanation. I thought earlier behavior was due to combination of both cards. I will update all other button-cards with the same aspect_ratio.

![Screen Shot 2020-06-16 at 1 22 55 PM](https://user-images.githubusercontent.com/16169720/84812783-8bb45400-afd4-11ea-9d37-3c20c71166fb.png)

```
          - type: horizontal-stack
            cards:
              - type: 'custom:button-card'
                template: blank_card_2px_width_style

              - type: custom:decluttering-card
                template: motion_sensors_battery_square
                variables:
                  - name: Bedroom
                  - entity: binary_sensor.wyzesense_777bfd2e
                  - entity2: sensor.tmpl_wyze_br_motion_sensor_battery

              - type: 'custom:button-card'
                template: blank_card_2px_width_style

              - type: custom:decluttering-card
                template: motion_sensors_battery_square
                variables:
                  - name: Laundry
                  - entity: binary_sensor.wyzesense_77a5f319
                  - entity2: sensor.tmpl_wyze_lr_motion_sensor_battery

              - type: custom:button-card
                color_type: blank-card
              - type: custom:button-card
                color_type: blank-card
              - type: custom:button-card
                color_type: blank-card
```
