### ISSUE TITLE
box-shadow on the wrong div when using the card?

### ISSUE THREAD

**Issue by chenchen119** [custom-cards/decluttering-card#3]
I am having a weird problem where using the decluttering card with vertical-stack-in-card would not show the standard box-shadow that comes with every card on the UI.

![image](https://user-images.githubusercontent.com/4780124/59152381-8999db80-89f7-11e9-9e96-1760ee5e1010.png)

Example below:
```
  - type: 'custom:vertical-stack-in-card'
    cards:
      - type: horizontal-stack
        cards:
          - type: 'custom:button-card'
            entity: light.home_theatre
            icon: 'mdi:movie-roll'
            name: Pot lights
            layout: icon_name
            styles:
              card:
                - height: 88px
                - width: 180px
              name:
                - font-size: 15px
                - font-weight: bold
                - text-transform: uppercase
          - type: entities
            entities:
              - type: 'custom:slider-entity-row'
                entity: light.home_theatre
                icon: 'mdi:lamp'
                full_row: true
                hide_state: true
  - type: 'custom:decluttering-card'
    template: dimmer_button_slider
    variables:
      - entity: light.home_theatre
      - icon: movie-roll
      - name: Pot lights
```

The decluttering_card_template:
```
decluttering_templates:
  dimmer_button_slider:
    type: 'custom:vertical-stack-in-card'
    cards:
      - type: horizontal-stack
        cards:
          - type: 'custom:button-card'
            entity: '[[entity]]'
            icon: 'mdi:[[icon]]'
            name: '[[name]]'
            layout: icon_name
            styles:
              card:
                - height: 88px
                - width: 180px
              name:
                - font-size: 15px
                - font-weight: bold
                - text-transform: uppercase
          - type: entities
            entities:
              - type: 'custom:slider-entity-row'
                entity: '[[entity]]'
                icon: 'mdi:[[icon]]'
                full_row: true
                hide_state: true
```

Tested it with button-card and works fine.
When I did a dev inspect, it seems the box-shadow is set on a lower div.. that is as much I can check..

Just tested on 0.2.0 as well.
