### ISSUE TITLE
Custom element doesn't exist: decluttering-card + JS console uncaught exception

### ISSUE THREAD

**Issue by wsw70** [custom-cards/decluttering-card#31]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

0.6.3

**Last working release (if known):**

**Browser and Operating System:**

Chrome 84, HA on official docker image

**Description of problem:**

I tried to install the card, but it fails with 

![image](https://user-images.githubusercontent.com/1345886/90913136-1a31c100-e3dc-11ea-96c9-a7997376de91.png)

The configuration is 

```
  - url: /hacsfiles/decluttering-card/decluttering-card.js
    type: module
```

It is then used as 

```
decluttering_templates:
  michael:
    card:
      entities:
        - switch.michael_lampe_haute
        - light.michael_mur
        - light.michael_bureau_gauche
        - light.michael_bureau_droite
      title: Michael
      type: entities
      state_color: true

title: Maison
views:
  - badges:
      - device_tracker.oppo_reno
      - device_tracker.galaxy_s9
      - device_tracker.mi9_mi9
      - device_tracker.mi9tpro_t_l_phonem
    cards:
      - type: custom:decluttering-card
        template: michael
(...)
```

**Javascript errors shown in the web inspector (if applicable):**

```
chunk.c136a66895309b59c3fe.js:1 Uncaught (in promise) https://hass.swtk.eu/hacsfile/decluttering-card.js
o.onerror @ chunk.c136a66895309b59c3fe.js:1
error (async)
(anonymous) @ chunk.c136a66895309b59c3fe.js:1
r @ chunk.c136a66895309b59c3fe.js:1
s @ chunk.c136a66895309b59c3fe.js:1
(anonymous) @ chunk.c136a66895309b59c3fe.js:21843
s @ chunk.c136a66895309b59c3fe.js:21843
(anonymous) @ chunk.c136a66895309b59c3fe.js:25455
Promise.then (async)
value @ chunk.c136a66895309b59c3fe.js:25455
value @ chunk.c136a66895309b59c3fe.js:25455
performUpdate @ app.664a8247.js:1
_enqueueUpdate @ app.664a8247.js:1
async function (async)
_enqueueUpdate @ app.664a8247.js:1
_requestUpdate @ app.664a8247.js:1
initialize @ app.664a8247.js:1
initialize @ app.664a8247.js:1
w @ app.664a8247.js:1
A @ app.664a8247.js:1
r @ chunk.c136a66895309b59c3fe.js:25230
value @ app.664a8247.js:44798
value @ app.664a8247.js:44798
_currentLoadProm.c.then._currentLoadProm @ app.664a8247.js:44798
Promise.then (async)
value @ app.664a8247.js:44798
performUpdate @ app.664a8247.js:1
_enqueueUpdate @ app.664a8247.js:1
async function (async)
_enqueueUpdate @ app.664a8247.js:1
_requestUpdate @ app.664a8247.js:1
set @ app.664a8247.js:1
value @ app.664a8247.js:44798
value @ app.664a8247.js:48086
value @ app.664a8247.js:48086
performUpdate @ app.664a8247.js:1
_enqueueUpdate @ app.664a8247.js:1
async function (async)
_enqueueUpdate @ app.664a8247.js:1
_requestUpdate @ app.664a8247.js:1
initialize @ app.664a8247.js:1
w @ app.664a8247.js:1
r @ app.664a8247.js:44798
r @ app.664a8247.js:48086
_clone @ app.664a8247.js:1
__commitTemplateResult @ app.664a8247.js:1
commit @ app.664a8247.js:1
a @ app.664a8247.js:1
A.render @ app.664a8247.js:1
update @ app.664a8247.js:1
performUpdate @ app.664a8247.js:1
_enqueueUpdate @ app.664a8247.js:1
async function (async)
_enqueueUpdate @ app.664a8247.js:1
_requestUpdate @ app.664a8247.js:1
initialize @ app.664a8247.js:1
initialize @ app.664a8247.js:1
w @ app.664a8247.js:1
A @ app.664a8247.js:1
n @ app.664a8247.js:48086
_clone @ app.664a8247.js:1
__commitTemplateResult @ app.664a8247.js:1
commit @ app.664a8247.js:1
update @ app.664a8247.js:1
__commitTemplateResult @ app.664a8247.js:1
commit @ app.664a8247.js:1
a @ app.664a8247.js:1
A.render @ app.664a8247.js:1
update @ app.664a8247.js:1
performUpdate @ app.664a8247.js:1
_enqueueUpdate @ app.664a8247.js:1
async function (async)
_enqueueUpdate @ app.664a8247.js:1
_requestUpdate @ app.664a8247.js:1
set @ app.664a8247.js:1
value @ app.664a8247.js:40600
(anonymous) @ app.664a8247.js:40600
n @ core.abb95f18.js:1
(anonymous) @ core.abb95f18.js:1
Promise.then (async)
a @ core.abb95f18.js:1
u @ core.abb95f18.js:1
subscribe @ core.abb95f18.js:1
u @ core.abb95f18.js:1
(anonymous) @ core.abb95f18.js:1
Promise.then (async)
194 @ core.abb95f18.js:1
r @ core.abb95f18.js:1
(anonymous) @ core.abb95f18.js:1
(anonymous) @ core.abb95f18.js:1
```

**Additional information:**
