### ISSUE TITLE
Any way to use this for UI managed dashboards?

### ISSUE THREAD

**Issue by andreasbrett** [custom-cards/decluttering-card#42]
I can't seem to figure out how/where to add the decluttering templates definitions when using UI managed lovelace dashboards. Could someone point me in the right direction?

What I tried was changing my lovelace config from this:

```
lovelace:
  mode: storage
```

to this

```
lovelace:
  mode: storage

  decluttering_templates:
    my_first_template:     # This is the name of a template
      default:
        - icon: fire
      card:
        type: custom:button-card
        name: '[[name]]'
        icon: 'mdi:[[icon]]'
```

But this is not valid for the lovelace configuration:

`Invalid config for [lovelace]: [decluttering_templates] is an invalid option for [lovelace].`
