### ISSUE TITLE
Feature request: Fallback support

### ISSUE THREAD

**Issue by marrobHD** [custom-cards/decluttering-card#44]
I would like to have a fallback support for example for the icon so that if no icon got specified in the card it will fall back to the fallback icon.

```yaml
decluttering_templates:
  my_first_template:     # This is the name of a template
    default:
      - icon: fire
    card:
      type: custom:button-card
      icon: [[icon]]
        fallback: mdi:alert
      name: '[[name]]'
```

It could look something like this.
