### ISSUE TITLE
layout-card mediaquery doesn't work when contained in a decluttering-card

### ISSUE THREAD

**Issue by MadMaxMcKinney** [custom-cards/decluttering-card#46]
So I've got a simple grid from layout_card:

```yaml
base_myhomekit_card_grid:

  # Detault vars ####
  default:
    - cards: ""

  card:
    type: custom:layout-card
    layout_type: grid
    layout_options:
      grid-template-columns: 1fr 1fr 1fr 1fr 1fr
      grid-template-rows: auto
      grid-gap: 8px
      mediaquery:
      "(max-width: 650px)":
        grid-template-columns: 1fr 1fr 1fr
    cards: '[[cards]]'
```

However, the mediaquery doesn't work for some reason. If I use the layout-card on its own and not as a template for the decluttering-card everything works as it should. 

What's going on here?
