### ISSUE TITLE
Decluttering not possible with conditional row? reports missing card

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/decluttering-card#48]
**Checklist:**

- [X ] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:**
latest
**Last working release (if known):**
don tknow
**Browser and Operating System:**
Any browser on Mac

**Description of problem:**

creating a decluttering for many repeating conditional rows:

```
      - type: conditional
        conditions:
          - entity: media_player.googlehome_library
            state_not: unavailable
        row:
          entity: input_boolean.googlehome_library
          state_color: true
```

with decl. template:

```
card:
  type: conditional
  conditions:
    - entity: media_player.googlehome_[[id]]
      state_not: unavailable
  row:
    entity: input_boolean.googlehome_[[id]]
    state_color: true
```

doesnt work and reports below error

**Javascript errors shown in the web inspector (if applicable):**

```

```
<img width="1133" alt="Schermafbeelding 2022-03-28 om 17 41 49" src="https://user-images.githubusercontent.com/33354141/160435886-f8111803-55e3-471e-b14f-1a83066acd47.png">

can clearly see the variables are replaced as they should:

<img width="501" alt="Schermafbeelding 2022-03-28 om 16 41 27" src="https://user-images.githubusercontent.com/33354141/160434933-d765beaa-1894-4545-bc16-155fbb6d70ef.png">

**Additional information:**

Can we not use decluttering in a conditional row? Or am I missing another important config option.
Please have a look?
thanks

**Comment by mathmaniac43** [comment]
Hello @Mariusthvdb. I just found the decluttering card today and was able to apply it to a bunch of my conditional cards, and things seem to work for me. I am using HA 2022.5.5 and installed the `Decluttering Card` via HACS.

I do not know if the [Conditional Card](https://www.home-assistant.io/dashboards/conditional/) has changed its interface recently, but I do not believe that it supports the `row` YAML key, but only the `card` YAML key. Here is an example that I used in my Lovelace YAML (via the web UI).

```yaml
decluttering_templates:
  template_healthcheck:
    card:
      type: conditional
      conditions:
        - entity: '[[entity]]'
          state_not: 'on'
      card:
        type: entity
        entity: '[[entity]]'
        attribute: last_ping
```

You may need to use the [Entity Card](https://www.home-assistant.io/dashboards/entity/) or [Entities Card](https://www.home-assistant.io/dashboards/entities/) in order to get your entity to work with the `Decluttering Card`.

Hope that helps.

**Comment by ildar170975** [comment]
> but I do not believe that it supports the `row` YAML key, but only the `card` YAML key

You may display a row wrapped into `hui-element` card.

Compare these templates:
```
  decl_conditional:
    card:
      type: conditional
      conditions:
        - entity: '[[SENSOR_CHECK]]'
          state: 'on'
      row:
        entity: '[[SENSOR_SHOW]]'
  decl_conditional_2:
    card:
      type: custom:hui-element
      row_type: conditional
      conditions:
        - entity: '[[SENSOR_CHECK]]'
          state: 'on'
      row:
        entity: '[[SENSOR_SHOW]]'
```

```
type: entities
entities:
  - entity: input_boolean.test_boolean
  - type: custom:decluttering-card
    template: decl_conditional
    variables:
      - SENSOR_CHECK: input_boolean.test_boolean
      - SENSOR_SHOW: sun.sun
  - type: custom:decluttering-card
    template: decl_conditional_2
    variables:
      - SENSOR_CHECK: input_boolean.test_boolean
      - SENSOR_SHOW: sun.sun
```
![изображение](https://user-images.githubusercontent.com/71872483/169898845-ac96a4f3-7de5-4e96-a5d9-99d47fca843a.png)

**Comment by Mariusthvdb** [comment]
yes, I should have updated the first post long time ago, sorry about that:
```
card:
  type: custom:hui-element
  row_type: conditional
  conditions:
    - entity: media_player.googlehome_[[id]]
      state_not: unavailable
  row:
    entity: input_boolean.googlehome_[[id]]
    state_color: true
```

is what I've been using for those for some time now

will close as this seems to be solved by that construction.
