### ISSUE TITLE
Using !Include to templates in .yaml

### ISSUE THREAD

**Issue by OscarGonz95** [custom-cards/decluttering-card#57]
Hello,

My decluttering templates are taking too much code lines and im looking to split my code in different .yaml files.

For now im didnt find any solution on the old posts, so it is possible to use !include my_template.yaml??? 

I would appreciate some help!

Thanks

**Comment by ildar170975** [comment]
As an example:

configuration.yaml:
```
homeassistant:
  ...
  allowlist_external_dirs:
    ...
    - /config/lovelace
...
lovelace: !include lovelace/lovelace.yaml
```

lovelace/lovelace.yaml:
```
mode: storage
dashboards:
  ...
  system:
    mode: yaml
    title: System
    icon: mdi:home-assistant
    show_in_sidebar: true
    require_admin: false
    filename: lovelace/lovelace-system.yaml
```
lovelace/lovelace-system.yaml:
```
decluttering_templates: !include_dir_merge_named templates-decluttering/
views:
  - !include views/system/general.yaml
  ...
```
Folder `lovelace/templates-decluttering`:
```
..
template_1.yaml
template_2.yaml
```
lovelace/templates-decluttering/template_1.yaml:
```
template_1:
  default:
    ...
  card:
    ...
```
So, each dashboard file (like "lovelace-system.yaml") should include that `decluttering_templates: !include_dir_merge_named templates-decluttering/` string to have your templates available.

**Comment by OscarGonz95** [comment]
I'm getting some issues following your steps.
Copy everything and creating the folder + lovelace.yaml. On lovelace-system.yaml I did just for test a fast view instead of import.
![image](https://user-images.githubusercontent.com/51195667/205897558-32642644-e6e7-4150-8e8e-4d79376076f7.png)

```
decluttering_templates: !include_dir_merge_named templates-decluttering/
views:
  - title: Test
    cards:
      - type: picture
        image: https://demo.home-assistant.io/stub_config/t-shirt-promo.png
        tap_action:
          action: none
        hold_action:
          action: none
```


 Deleting thse"..." from your example code. I try to validate the config and i get this issue: 

"Invalid config for [lovelace]: Url path needs to contain a hyphen (-) for dictionary value @ data['lovelace']['dashboards']. Got OrderedDict([('system', OrderedDict([('mode', 'yaml'), ('title', 'System'), ('icon', 'mdi:home-assistant'), ('show_in_sidebar', True), ('require_admin', False), ('filename', 'lovelace/lovelace-system.yaml')]))]). (See /config/configuration.yaml, line 67)." 


Maybe a mistake on the !import

`lovelace: !include lovelace/lovelace.yaml`

to 

`lovelace: !include /lovelace/lovelace.yaml`

But anyways i had error:

Error loading /config/configuration.yaml: in "/config/configuration.yaml", line 68, column 11: Unable to read file /lovelace/lovelace.yaml.


Thanks for your help!
