### ISSUE TITLE
!include is not supported? Can it?

### ISSUE THREAD

**Issue by MarsWarrior** [custom-cards/decluttering-card#6]
I tried to use the !include statement to have some sort of re-use within templates, but I get errors (mapping errors, expecting ':', etc.), so include doesn't seem to be supported or I am doing something wrong 😄.

What I would want for instance:

- Have a template part with generic defaults
- Add / override these in specific templates

So for template 'specific1':
```
default:
!include 'template-defaults.yaml' (defines defaults for valuex, valuey and valuez)
# Now override some values
  - valuex: 11
  - valuey: 22
```

And template 'specific2':
```
default:
!include 'template-defaults.yaml' (defines defaults for valuex, valuey and valuez)
# Now override some values
  - valuex: 11
  - valuez: 33
```
