### ISSUE TITLE
Problem with decluttering card and lovelace_gen together

### ISSUE THREAD

**Issue by Aleborg** [custom-cards/decluttering-card#61]
**Checklist:**

- [x ] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**
latest

**Last working release (if known):**

**Browser and Operating System:**
Chrome
Winows 10

**Description of problem:**

I'm trying to use decluttering card and lovelace_gen together but ran in to a problem where variables from the decluttering card isn't parsed the way they're supposed to with lovelace_gen.

I have this declaration: `decluttering_templates: !include test_template.yaml`

test_template.yaml:
```yaml
# lovelace_gen
test_template:
  card:
    {% set showIt = '[[showMe]]' %}
    {% if showIt == 'a' %}
    type: custom:mushroom-title-card
    title: '{{showIt}} - a'
    {% elif showIt == 'b' %}
    type: custom:mushroom-entity-card
    entity: sensor.my_sensor
    {% else %}
    type: custom:mushroom-title-card
    title: '{{showIt}} - failed'
    {% endif %}
```

and my decluttering-card:
```yaml
- type: custom:decluttering-card
  template: test_template
  variables:
    - showMe: 'a'


- type: custom:decluttering-card
  template: test_template
  variables:
    - showMe: 'b'
```

the problem is that lovelace_gen seems to interpret `[[showMe]]` as `'showMe'` instead of `'a'` or `'b'`.
The output becomes `a - failed` or `b - failed`.

Is there a way to solve this?

**Comment by Aleborg** [comment]
I just now noticed that the *decluttering card* use javascript for variables so it won't be possible to pass those into jinja which lovelace_gen is using, so I guess one of these 2 has to be excluded from my code.

So now the question is how to solve this problem. Instead of an example like above I'll show you one of my real case scenarios.

I'm using  [tabbed-card](https://github.com/kinghat/tabbed-card) and what I need is to show/hide tabs depending on the existence of entities in an area.
So let's say I have 2 tabs:

```yaml
  type: custom:tabbed-card
  tabs:
    # LIGHTS - section
    ##########
    - card:
        - type: custom:auto-entities
          card:
            type: entities
          filter:
            - domain: light
              area: '{{area_name}}' # this comes from another file using lovelace_gen's !include
      attributes:
        label: 'Lights'

    - card:
    # MEDIA - section
    ##########
        - type: custom:auto-entities
          card:
            type: entities
          filter:
            - domain: media_player
              area: '{{area_name}}' # this comes from another file using lovelace_gen's !include
      attributes:
        label: 'Media'
```
If there's no light entities, then the *LIGHTS - section* shouldn't be shown, that includes the `- card`part that starts the section (each `- card` is a tab). Same goes for the *MEDIA - section*.

I tried using *decluttering card* and *card-mod* to add the css `display: none`, it works, but to get it to actually work in a browser I had to do a hard refresh (ctrl+r) of the page every time cause it starts with showing all the tabs, after the refresh it would hide the tab.

So any ideas on how to solve this problem?
This is for my custom dashboard [Aleborg Frontend](https://github.com/Aleborg/homeassistant-aleborg-frontend).
I really wish that they could add templating possibilities to the frontend...
