### ISSUE TITLE
Default referencing variable

### ISSUE THREAD

**Issue by clinta** [custom-cards/decluttering-card#62]
I'd like to be able to reference variables in defaults. For example:

```yaml
decluttering_templates:
  room_card:
    default:
      light_entity: 'light.[[room]]'
  card:
    type: entity
    entity: '[[light_entity]]'
```

That template could then be used with either of the following:

```yaml
- type: custom:decluttering-card
  template: room_card
  variables:
    - room: office
```

```yaml
- type: custom:decluttering-card
  template: room_card
  variables:
    - room: office
    - light_entity: light.office_floor_lamp
```
