### ISSUE TITLE
decluttering-card references appear broken with Core 2023.4.0

### ISSUE THREAD

**Issue by Qoheleth** [custom-cards/decluttering-card#65]
**Release with the issue:**
2023.4.0
**Last working release (if known):**
2023.3.6
**Browser and Operating System:**
Edge on Windows 11 also on Windows app and on Android App
**Description of problem:**
All previously working decluttering templates now display an error message like this:
![decluttering error](https://user-images.githubusercontent.com/2237808/230215036-df06d510-cebb-4829-a883-201428369dba.png)
**Additional information:**
decluttering card template:
```
# card with automated light control
  auto-light-thing:
    card:
      type: 'custom:button-card'
      entity: '[[thing_entity]]'
      name: '[[thing_name]]'
      template: standard-button
      triggers_update: all
      aspect_ratio: '[[aspect_ratio]]'
      styles:
        grid:
          - position: relative
        custom_fields:
          lt:
            - position: absolute
            - right: 0%
            - top: 0%
            - height: 20px
            - width: 20px
      custom_fields:
        lt: |
          [[[
            var icon = "mdi:alpha-a-circle-outline";
            var color = "darkGrey";
            var status = states['[[light_entity]]'].state;
            if (status == 'on') {
              icon = "mdi:alpha-a-circle";
              color = "darkGreen";
            }
            return `<ha-icon icon="${icon}"
            style="width 18px; height: 18px; color: ${color};"></ha-icon>`
          ]]]
      hold_action:
        action: call-service
        service: homeassistant.toggle
        service_data:
          entity_id: '[[light_entity]]'
      state:
        - value: 'on'
          id: value_on
          icon: '[[thing_icon_on]]'
        - value: 'off'
          id: value_off
          icon: '[[thing_icon_off]]'
```
decluttering card use in ui-lovelace.yaml:
```
                - type: 'custom:decluttering-card'
                  template: auto-light-thing
                  variables:
                    - thing_entity: switch.grow_light_outlet
                    - thing_name: 'Grow Lt'
                    - light_entity: input_boolean.grow_light_automated
                    - thing_icon_on: 'mdi:lightbulb-on'
                    - thing_icon_off: 'mdi:lightbulb-outline'
                    - aspect_ratio: 1/1.1
```
