### ISSUE TITLE
Cannot read properties issue since 2023.4.x

### ISSUE THREAD

**Issue by SupremeSports** [custom-cards/decluttering-card#67]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v1.0.0
**Last working release (if known):**

**Browser and Operating System:**
Chrome on Win10, HA App on iOS

**Description of problem:**
Unable to use standard HACS ressource reference, have to manually enter it.
Problem occurs since 2023.4.x (went from 2023.3.6 to 2023.4.4 and got the issue). Tested on 2 different HA systems and same thing happens.

Error message on each declut card: ```Cannot read properties of null (reading'config')```
![Error message](https://user-images.githubusercontent.com/13887820/232262145-e829cf20-2cdd-4480-ba42-b64dd09ba6e3.png)

Into resource.yaml:
Normal reference: 
```
  - url: /hacsfiles/decluttering-card/decluttering-card.js
    type: module
```
Modified reference: 
```
  - url: /local/community/decluttering-card/decluttering-card.js
    type: module
```

**Comment by electricJP** [comment]
I have the same issue but I already use the modified reference


lovelace:
  mode: yaml
  resources:
     - url: /hacsfiles/lovelace-hui-element/hui-element.js
       type: module
     - url: /local/community/decluttering-card/decluttering-card.js
       type: module
     - url: /local/community/button-card/button-card.js
       type: module
     - url: /local/community/apexcharts-card/apexcharts-card.js
       type: module
     - url: /local/community/bar-card/bar-card.js
       type: module

**Comment by brainpt** [comment]
> I have the same issue but I already use the modified reference
> 
> lovelace: mode: yaml resources: - url: /hacsfiles/lovelace-hui-element/hui-element.js type: module - url: /local/community/decluttering-card/decluttering-card.js type: module - url: /local/community/button-card/button-card.js type: module - url: /local/community/apexcharts-card/apexcharts-card.js type: module - url: /local/community/bar-card/bar-card.js type: module

I'm also facing the same issue, running the latest decluttering version (and already had the modified reference) and with HA 2023.4.6 version. 

`Cannont read properties of null (reading 'config')`

**Comment by rcdailey** [comment]
I'm having this issue as well. What do you guys mean by "modified reference"? Is that referring to the `/hacsfiles` URL paths in the resources.yaml file?

**Comment by luixal** [comment]
Same problem on a fresh install using HACS.

**Comment by brainpt** [comment]
> I'm having this issue as well. What do you guys mean by "modified reference"? Is that referring to the `/hacsfiles` URL paths in the resources.yaml file?

Yes. That's it.

**Comment by rcdailey** [comment]
Can you point me to where that change is documented? I haven't touched my URL paths in a LONG time and I'm unaware of any deprecations or the like.

**Comment by RandyLevensalor** [comment]
I ended up uninstalling decluttering-card from HACS, then reinstalling it.

I changed the resource import from:

```yaml
    - url: /local/community/decluttering-card/decluttering-card.js
      type: module
```

to:

```yaml
    - url: /hacsfiles/decluttering-card/decluttering-card.js
      type: module
```

It's now working.  I'm not entirely sure why.  I had tried the hacsfiles url before reinstalling and didn't work. This last update up home assistant had all kinds of issess, many of which required extra restarts.

**Comment by Nerkyator** [comment]
I have same problem. Changing resource import doesn't fix :(

**HA version**: 2023.10.1
**Decluttering card version**: last
**Installation method**: HACS
**Dashboard**: storage 
Decluttering card added in resources through "three dots method" from UI

Just created decluttering_templates.yaml file with

```
decluttering_templates:
  cameras:
    card:
      camera_view: live
      type: picture-glance
      title: "[[title]]"
      entities: []
      camera_image: "[[camera]]"
      theme: Mushroom Shadow
      view_layout:
        grid-area: "[[gridArea]]"
```
Dashboard page yaml file: 

```
decluttering_templates: !include ../common/decluttering_templates.yaml

type: custom:layout-card
layout_type: custom:grid-layout
view_layout:
  grid-area: content
layout:
  margin: 0px 0px 0px 0px
  card_margin: 0px 0px 0px 0px
  grid-template-columns: auto
  grid-template-rows: auto
  grid-template-areas: |
    "road terrace"
    "porch ."
cards:
  - type: custom:decluttering-card
    template: cameras
    variables:
      - title: Road
      - camera: camera.g4_dome_high
      - gridArea: road
```

Opening dashboard I have the well known error:

```
Cannot read properties of undefined (reading 'cameras')
type: custom:decluttering-card
template: cameras
variables:
  - title: Road
  - camera: camera.g4_dome_high
  - gridArea: road
```

**Comment by danielbrunt57** [comment]
I've just implemented this card for the first time and I had zero issues, once I wrapped my head around how it works.

Installed card via HACS.
![image](https://github.com/custom-cards/decluttering-card/assets/49846893/e94be174-65f4-4e5d-bf20-2fda7288acee)

Verified resource added.
![image](https://github.com/custom-cards/decluttering-card/assets/49846893/98c41617-ec01-4856-8f83-f5470b3408d2)

Added decluttering template to lovelace dashboard via raw config editor.
![image](https://github.com/custom-cards/decluttering-card/assets/49846893/09a8d9df-8b38-4fd6-9975-6d62f92c916b)

Edited my existing 6 cards to use the decluttering card.
```
type: vertical-stack
cards:
  - type: custom:mushroom-title-card
    title: ''
    subtitle: Kitchen
    alignment: center
  - type: horizontal-stack
    cards:
      - type: custom:decluttering-card
        template: iblinds
        variables:
          - blind: kitchen_blind_1
          - display_name: Blind 1
      - type: custom:decluttering-card
        template: iblinds
        variables:
          - blind: kitchen_blind_2
          - display_name: Blind 2
      - type: custom:decluttering-card
        template: iblinds
        variables:
          - blind: kitchen_blind_3
          - display_name: Blind 3
view_layout:
  column: 1
```
![image](https://github.com/custom-cards/decluttering-card/assets/49846893/f14d3361-e115-4e5e-ba27-6cffc6c6c340)
```
type: custom:mod-card
card_mod:
  style:
    hui-horizontal-stack-card $: |
      div#root > :first-child {
        width: 66%;
        flex: auto; 
      }
      div#root > :last-child {
        width: 33%;
        flex: auto; 
      }
card:
  type: horizontal-stack
  cards:
    - type: vertical-stack
      cards:
        - type: vertical-stack
          cards:
            - type: custom:mushroom-title-card
              title: ''
              subtitle: Living Room
              alignment: center
            - type: horizontal-stack
              cards:
                - type: custom:decluttering-card
                  template: iblinds
                  variables:
                    - blind: living_room_blind
                    - display_name: Window
                - type: custom:decluttering-card
                  template: iblinds
                  variables:
                    - blind: patio_door_blind
                    - display_name: Patio Door
    - type: vertical-stack
      cards:
        - type: custom:mushroom-title-card
          title: ''
          subtitle: Master Bedroom
          alignment: center
        - type: horizontal-stack
          cards:
            - type: custom:decluttering-card
              template: iblinds
              variables:
                - blind: bedroom_blind
                - display_name: Window
view_layout:
  column: 1
```
![image](https://github.com/custom-cards/decluttering-card/assets/49846893/a278925b-81ef-4455-b1f2-b94de98af005)

**Comment by Schiri** [comment]
I'm facing the same issue, tried both
`- url: /hacsfiles/decluttering-card/decluttering-card.js
     type: module`
and
`- url: /local/community/decluttering-card/decluttering-card.js
     type: module`
    
but none worked. Implementation:

`decluttering_templates:
  sonos:     # This is the name of a template
    card:
      type: custom:mini-media-player
      entity: '[[entity_1]]'
      artwork: cover
      max_volume: 40
      volume_stateless: true
      toggle_power: false
      scale: 2
      hide:
        power: true
        volume_level: false
      shortcuts: !include media_buttons.yaml
      speaker_group: !include speaker_group.yaml

cards:
  - type: custom:decluttering-card
    template: sonos
    variables:
      - entity_1: media_player.living_room

  - type: custom:decluttering-card
    template: sonos
    variables:
      - entity_1: media_player.kitchen

  - type: custom:decluttering-card
    template: sonos
    variables:
      - entity_1: media_player.bathroom

  - type: custom:decluttering-card
    template: sonos
    variables:
      - entity_1: media_player.bedroom

  - type: custom:decluttering-card
    template: sonos
    variables:
      - entity_1: media_player.unnamed_room`

HA Core 2024.2.5
HA Frontend 20240207.1

**Comment by fireinice** [comment]
It seems that some types of card are not well supported. I got the exactly same error if I write with

```yaml
decluttering_templates:
    climate_template:
       - card:
          type: tile
          entity: "[[climate_entity]]"
          features:
            - type: target-temperature
            - type: "climate-hvac-modes"
              hvac_modes:
                - auto
                - heat_cool
                - heat
                - cool
                - dry
                - "off"
```

but if wrap it with vertical-stack, all problems are gone.
The configuration below would work:
```yaml
decluttering_templates:
    climate_template:
       card:
           type: custom:vertical-stack-in-card
           cards:
               - type: conditional
                 conditions:
                     - entity: "[[climate_entity]]"
                       state: "off"
                 card:
                     type: tile
                     entity: "[[climate_entity]]"
                 features:
                    - type: target-temperature
                    - type: "climate-hvac-modes"
                      hvac_modes:
                         - auto
                         - heat_cool
                         - heat
                         - cool
                         - dry
                         - "off"
```
