### ISSUE TITLE
Decluttering for tile cards not working

### ISSUE THREAD

**Issue by freeDom-** [custom-cards/decluttering-card#75]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

v 1.0.0

**Last working release (if known):**

**Browser and Operating System:**

Firefox 120.0.1 (64-Bit)

**Description of problem:**

Decluttering does not work when using a tile card.

```
decluttering_templates:
  tile_test:
    card:
      - type: tile
        entity: '[[entity_id]]'
```

```
  - type: custom:decluttering-card
    template: tile_test
    variables:
      - entity_id: binary_sensor.test_sensor
```

**Javascript errors shown in the web inspector (if applicable):**

```
card undefined Error: No card type configured
    h create-element-base.ts:207
    c create-element-base.ts:170
    f create-card-element.ts:102
    _createCard decluttering-card.js:192
```

**Additional information:**

**Comment by ildar170975** [comment]
Wrong code.
```
  tile_test:
    card:
      type: tile
      entity: '[[entity_id]]'
```
