### ISSUE TITLE
problem when using card with 'grid-area:'

### ISSUE THREAD

**Issue by moonbit5** [custom-cards/decluttering-card#81]
Hi – I'm seeing an issue where the decluttering card is breaking out of the grid when using mediaquery. The card is only sitting in the grid when the mediaquery matches #phone.  #default results in the card sitting outside the grid. 

What could be causing this to happen? Does the card support custom grids? 

Card which has an issue:

```
  - type: custom:decluttering-card
    template: top_navigation
    variables:
      - grid_area: main2
```

Template:

```
top_navigation:
  card:
    type: vertical-stack
    view_layout:
      grid-area: "[[grid_area]]"
    cards:
      - type: horizontal-stack
        cards: ...
```
Loaded via:

`decluttering_templates: !include_dir_merge_named "/config/material-tablet-yaml/templates/"`

Grid:

```
layout:
  #default
  grid-template-columns: 2% 58% 80px 15% 80px
  grid-template-rows: 1fr
  grid-template-areas: |
    ". top top top ."
    "main1 main2 main2 main2 ."
    ". title title . ."
    "side side2 . side3 side4"
    "footer footer1 footer1 . ."
  #phone
  mediaquery:
    "(max-width: 600px)":
      grid-template-columns: 100%
      grid-template-rows: 1fr
      grid-template-areas: |
        "top"
        "main2"
        "title"
        "side2"
        "side3"
        "footer1"
```

<img width="249" alt="Screenshot 2024-05-26 at 14 34 49" src="https://github.com/custom-cards/decluttering-card/assets/57290277/4c1c6032-3d2c-4b84-8beb-0e9018927af1">
