### ISSUE TITLE
Question/suggestion example nesting templates

### ISSUE THREAD

**Issue by erkr** [custom-cards/decluttering-card#82]
I just explored the decluttering card a little. Great work!
One of my requirements is to nest templates, but can’t find any info nor examples. 
So I slightly modified the example in the readme to nest the first template into the second:

**Templates:**
``` 
decluttering_templates:
  my_first_template:
    default:
      - icon: fire
    card:
      type: button
      name: '[[name]]'
      icon: mdi:[[icon]]
      entity: '[[entity]]'
  my_second_template:
    card:
      type: custom:vertical-stack-in-card
      cards:
        - type: horizontal-stack
          cards:
            - type: custom:decluttering-card
              template: my_first_template
              variables:
                - name: Test Button 1
                - icon: arrow-up
                - entity: '[[entity_1]]'
            - type: custom:decluttering-card
              template: my_first_template
              variables:
                - name: Test Button 2
                - icon: arrow-down
                - entity: '[[entity_2]]'
``` 
**usage:**
``` 
type: custom:decluttering-card
template: my_second_template
variables:
  - entity_1: light.serre1
  - entity_2: light.serre2
``` 
And this works 👌:

**Now my question/suggestion:** 
Is this usage official supported? Or deemed to raise future issues?
If supported, it could be nice to add this example to the readme as well.

Thx Eric
