### ISSUE TITLE
[FR] Fallback value of a variable to another variable

### ISSUE THREAD

**Issue by clau-bucur** [custom-cards/decluttering-card#84]
**Describe the solution you'd like**
Is it possible to define the default value of a variable, as the value of another variable?

Someting like:
```
my_template:
  default:
    - history_entity: '[[entity]]'
  card:
    type: my_card
    entity: '[[entity]]'
    tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.more_info
        data:
          entity: '[[history_entity]]'
```

And when I call it withoiut specifying a value for `history_entity` it will use the value specified for the `entity` variable:
```
- type: custom:decluttering-card
  template: my_template
  variables:
    - entity: sensor.my_entity
```

**Comment by ildar170975** [comment]
Agree, a good idea, was thinking about same many times.

**Comment by droans** [comment]
Use a conditional card.

```
my_template:
  defaults:
    - history_entity: 'fake'
  card:
    type: vertical-stack
    cards:
      - type: conditional
        conditions:
          - condition: state
            entity: '[[ history_entity]]'
            state: "unavailable"
        card:
          - type: my_card
            entity: '[[entity]]'
            tap_action:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.more_info
                data:
                  entity: '[[entity]]'
      - type: conditional
        conditions:
          - condition: state
            entity: '[[ history_entity]]'
            state_not: "unavailable"
        card:
          - type: my_card
            entity: '[[entity]]'
            tap_action:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.more_info
                data:
                  entity: '[[history_entity]]'
```

A non-existent sensor will always return unavailable.
