### ISSUE TITLE
FR: Support visibility

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/decluttering-card#85]
**Is your feature request related to a problem? Please describe.**

the new visibility option is not supported, and we need to use conditional cards

**Describe the solution you'd like**

have decluttering-card support visibility

**Describe alternatives you've considered**

conditional card
**Additional context**

template:
```
card:
#   type: conditional
#   conditions:
#     - entity: switch.[[entity]]_privacy_mode
#       state_not: 'on'
#   card:
    type: picture-entity
    visibility:
      - entity: switch.[[entity]]_privacy_mode
        state_not: 'on'
    entity: camera.[[entity]]
  #     name: '[[name]]'
    show_state: false
    show_name: false
    camera_view: live
```

and card in  dashboard:
```
  - type: custom:decluttering-card
    template: camera_privacy
    variables:
      - entity: bijkeuken
      - name: Bijkeuken
 ```

as you can see in the above yaml, I tried to replace conditional card with a straight replacement using visibility
it does not work, and the card is displayed no matter the visibility options set.

I also checked the core picture-entity card for support of the visibility option, and yes, that works nicely when used verbosely like

```
  - type: picture-entity
    visibility:
      - entity: switch.bijkeuken_privacy_mode
        state_not: 'on'
    entity: camera.bijkeuken
  #     name: '[[name]]'
    show_state: false
    show_name: false
    camera_view: live
```
