### ISSUE TITLE
Support additional types

### ISSUE THREAD

**Issue by shaiger** [custom-cards/decluttering-card#88]
Apologies, I do not consider myself to be nor a YAML or an HA expert. 
For the very least I am hoping to learn about a new approach that I may have not considered in the past.

**Problem:**
I've become addicted to the ability to reuse config for cards. Decluttering templates make a huge difference for me in maintaining configurations across my dashboards and devices.
Over time I have accumulated a large number of dashboards and views. In fact, I have a certain baseline I use for all of my views and dashboards. What I lack is the ability to reuse "view:" configuration, just as I can do with my cards. 
My dashboard and view configuration is becoming more and more convoluted over time. 

**The solution I'd like:**
Here is a simple example for illustration:

```
template_view_base:
  view:
    title: '[[title]]'
    path: '[[path]]'
    type: sections
    max_columns: 10
    icon: '[[icon]]'
    dense_section_placement: true
    sections:
      - type: grid
        column_span: full
        cards: '[[cards]]'
```

Alternatives I've considered:

1. Replicate and clutter :(
2. Instead of managing customizations on top of the base in YAML, build a single stateful dashboard that can:
- manage state per device
- leverage some new configuration that will dictates which options to use per device
- contain the logic to select desired behaviors in run time instead of config time
